//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang.ServiceUser {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class user : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.export_bill[] export_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phone_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.role roleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.export_bill[] export_bill {
            get {
                return this.export_billField;
            }
            set {
                if ((object.ReferenceEquals(this.export_billField, value) != true)) {
                    this.export_billField = value;
                    this.RaisePropertyChanged("export_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_role {
            get {
                return this.id_roleField;
            }
            set {
                if ((this.id_roleField.Equals(value) != true)) {
                    this.id_roleField = value;
                    this.RaisePropertyChanged("id_role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.phone_numberField, value) != true)) {
                    this.phone_numberField = value;
                    this.RaisePropertyChanged("phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.role role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="role", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte add_roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte delete_roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string describeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte read_roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte update_roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.user[] usersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte add_role {
            get {
                return this.add_roleField;
            }
            set {
                if ((this.add_roleField.Equals(value) != true)) {
                    this.add_roleField = value;
                    this.RaisePropertyChanged("add_role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte delete_role {
            get {
                return this.delete_roleField;
            }
            set {
                if ((this.delete_roleField.Equals(value) != true)) {
                    this.delete_roleField = value;
                    this.RaisePropertyChanged("delete_role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string describe {
            get {
                return this.describeField;
            }
            set {
                if ((object.ReferenceEquals(this.describeField, value) != true)) {
                    this.describeField = value;
                    this.RaisePropertyChanged("describe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte read_role {
            get {
                return this.read_roleField;
            }
            set {
                if ((this.read_roleField.Equals(value) != true)) {
                    this.read_roleField = value;
                    this.RaisePropertyChanged("read_role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte update_role {
            get {
                return this.update_roleField;
            }
            set {
                if ((this.update_roleField.Equals(value) != true)) {
                    this.update_roleField = value;
                    this.RaisePropertyChanged("update_role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.user[] users {
            get {
                return this.usersField;
            }
            set {
                if ((object.ReferenceEquals(this.usersField, value) != true)) {
                    this.usersField = value;
                    this.RaisePropertyChanged("users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="export_bill", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class export_bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.export_bill_detail[] export_bill_detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal total_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.user userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.export_bill_detail[] export_bill_detail {
            get {
                return this.export_bill_detailField;
            }
            set {
                if ((object.ReferenceEquals(this.export_bill_detailField, value) != true)) {
                    this.export_bill_detailField = value;
                    this.RaisePropertyChanged("export_bill_detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_user {
            get {
                return this.id_userField;
            }
            set {
                if ((this.id_userField.Equals(value) != true)) {
                    this.id_userField = value;
                    this.RaisePropertyChanged("id_user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total_price {
            get {
                return this.total_priceField;
            }
            set {
                if ((this.total_priceField.Equals(value) != true)) {
                    this.total_priceField = value;
                    this.RaisePropertyChanged("total_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="export_bill_detail", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class export_bill_detail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.export_bill export_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_export_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.product productField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.export_bill export_bill {
            get {
                return this.export_billField;
            }
            set {
                if ((object.ReferenceEquals(this.export_billField, value) != true)) {
                    this.export_billField = value;
                    this.RaisePropertyChanged("export_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_export_bill {
            get {
                return this.id_export_billField;
            }
            set {
                if ((this.id_export_billField.Equals(value) != true)) {
                    this.id_export_billField = value;
                    this.RaisePropertyChanged("id_export_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="product", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.export_bill_detail[] export_bill_detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_manufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_saveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.import_bill_detail[] import_bill_detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.manufacturer manufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal sale_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.save saveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.export_bill_detail[] export_bill_detail {
            get {
                return this.export_bill_detailField;
            }
            set {
                if ((object.ReferenceEquals(this.export_bill_detailField, value) != true)) {
                    this.export_bill_detailField = value;
                    this.RaisePropertyChanged("export_bill_detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_manufacturer {
            get {
                return this.id_manufacturerField;
            }
            set {
                if ((this.id_manufacturerField.Equals(value) != true)) {
                    this.id_manufacturerField = value;
                    this.RaisePropertyChanged("id_manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_save {
            get {
                return this.id_saveField;
            }
            set {
                if ((this.id_saveField.Equals(value) != true)) {
                    this.id_saveField = value;
                    this.RaisePropertyChanged("id_save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.import_bill_detail[] import_bill_detail {
            get {
                return this.import_bill_detailField;
            }
            set {
                if ((object.ReferenceEquals(this.import_bill_detailField, value) != true)) {
                    this.import_bill_detailField = value;
                    this.RaisePropertyChanged("import_bill_detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.manufacturer manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturerField, value) != true)) {
                    this.manufacturerField = value;
                    this.RaisePropertyChanged("manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string product_info {
            get {
                return this.product_infoField;
            }
            set {
                if ((object.ReferenceEquals(this.product_infoField, value) != true)) {
                    this.product_infoField = value;
                    this.RaisePropertyChanged("product_info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal sale_price {
            get {
                return this.sale_priceField;
            }
            set {
                if ((this.sale_priceField.Equals(value) != true)) {
                    this.sale_priceField = value;
                    this.RaisePropertyChanged("sale_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.save save {
            get {
                return this.saveField;
            }
            set {
                if ((object.ReferenceEquals(this.saveField, value) != true)) {
                    this.saveField = value;
                    this.RaisePropertyChanged("save");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="manufacturer", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class manufacturer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.import_bill[] import_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phone_numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.product[] productsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.import_bill[] import_bill {
            get {
                return this.import_billField;
            }
            set {
                if ((object.ReferenceEquals(this.import_billField, value) != true)) {
                    this.import_billField = value;
                    this.RaisePropertyChanged("import_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_number {
            get {
                return this.phone_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.phone_numberField, value) != true)) {
                    this.phone_numberField = value;
                    this.RaisePropertyChanged("phone_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.product[] products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="save", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class save : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string content_saveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string imageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int percent_saveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.product[] productsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.save_date[] save_dateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content_save {
            get {
                return this.content_saveField;
            }
            set {
                if ((object.ReferenceEquals(this.content_saveField, value) != true)) {
                    this.content_saveField = value;
                    this.RaisePropertyChanged("content_save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image {
            get {
                return this.imageField;
            }
            set {
                if ((object.ReferenceEquals(this.imageField, value) != true)) {
                    this.imageField = value;
                    this.RaisePropertyChanged("image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int percent_save {
            get {
                return this.percent_saveField;
            }
            set {
                if ((this.percent_saveField.Equals(value) != true)) {
                    this.percent_saveField = value;
                    this.RaisePropertyChanged("percent_save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.product[] products {
            get {
                return this.productsField;
            }
            set {
                if ((object.ReferenceEquals(this.productsField, value) != true)) {
                    this.productsField = value;
                    this.RaisePropertyChanged("products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.save_date[] save_date {
            get {
                return this.save_dateField;
            }
            set {
                if ((object.ReferenceEquals(this.save_dateField, value) != true)) {
                    this.save_dateField = value;
                    this.RaisePropertyChanged("save_date");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="import_bill_detail", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class import_bill_detail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_import_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.import_bill import_billField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.product productField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal purchase_priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_import_bill {
            get {
                return this.id_import_billField;
            }
            set {
                if ((this.id_import_billField.Equals(value) != true)) {
                    this.id_import_billField = value;
                    this.RaisePropertyChanged("id_import_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_product {
            get {
                return this.id_productField;
            }
            set {
                if ((this.id_productField.Equals(value) != true)) {
                    this.id_productField = value;
                    this.RaisePropertyChanged("id_product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.import_bill import_bill {
            get {
                return this.import_billField;
            }
            set {
                if ((object.ReferenceEquals(this.import_billField, value) != true)) {
                    this.import_billField = value;
                    this.RaisePropertyChanged("import_bill");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int number {
            get {
                return this.numberField;
            }
            set {
                if ((this.numberField.Equals(value) != true)) {
                    this.numberField = value;
                    this.RaisePropertyChanged("number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.product product {
            get {
                return this.productField;
            }
            set {
                if ((object.ReferenceEquals(this.productField, value) != true)) {
                    this.productField = value;
                    this.RaisePropertyChanged("product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal purchase_price {
            get {
                return this.purchase_priceField;
            }
            set {
                if ((this.purchase_priceField.Equals(value) != true)) {
                    this.purchase_priceField = value;
                    this.RaisePropertyChanged("purchase_price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="import_bill", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class import_bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_manufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.import_bill_detail[] import_bill_detailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.manufacturer manufacturerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal total_priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_manufacturer {
            get {
                return this.id_manufacturerField;
            }
            set {
                if ((this.id_manufacturerField.Equals(value) != true)) {
                    this.id_manufacturerField = value;
                    this.RaisePropertyChanged("id_manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.import_bill_detail[] import_bill_detail {
            get {
                return this.import_bill_detailField;
            }
            set {
                if ((object.ReferenceEquals(this.import_bill_detailField, value) != true)) {
                    this.import_bill_detailField = value;
                    this.RaisePropertyChanged("import_bill_detail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.manufacturer manufacturer {
            get {
                return this.manufacturerField;
            }
            set {
                if ((object.ReferenceEquals(this.manufacturerField, value) != true)) {
                    this.manufacturerField = value;
                    this.RaisePropertyChanged("manufacturer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal total_price {
            get {
                return this.total_priceField;
            }
            set {
                if ((this.total_priceField.Equals(value) != true)) {
                    this.total_priceField = value;
                    this.RaisePropertyChanged("total_price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="save_date", Namespace="http://schemas.datacontract.org/2004/07/QLBH_PHONE_SERVICE.Models", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class save_date : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime date_startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int id_saveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BanHang.ServiceUser.save saveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_end {
            get {
                return this.date_endField;
            }
            set {
                if ((this.date_endField.Equals(value) != true)) {
                    this.date_endField = value;
                    this.RaisePropertyChanged("date_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date_start {
            get {
                return this.date_startField;
            }
            set {
                if ((this.date_startField.Equals(value) != true)) {
                    this.date_startField = value;
                    this.RaisePropertyChanged("date_start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id_save {
            get {
                return this.id_saveField;
            }
            set {
                if ((this.id_saveField.Equals(value) != true)) {
                    this.id_saveField = value;
                    this.RaisePropertyChanged("id_save");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BanHang.ServiceUser.save save {
            get {
                return this.saveField;
            }
            set {
                if ((object.ReferenceEquals(this.saveField, value) != true)) {
                    this.saveField = value;
                    this.RaisePropertyChanged("save");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUser.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckUser", ReplyAction="http://tempuri.org/IUser/CheckUserResponse")]
        bool CheckUser(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckUser", ReplyAction="http://tempuri.org/IUser/CheckUserResponse")]
        System.Threading.Tasks.Task<bool> CheckUserAsync(string email, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckEmailExisted", ReplyAction="http://tempuri.org/IUser/CheckEmailExistedResponse")]
        bool CheckEmailExisted(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/CheckEmailExisted", ReplyAction="http://tempuri.org/IUser/CheckEmailExistedResponse")]
        System.Threading.Tasks.Task<bool> CheckEmailExistedAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAllUser", ReplyAction="http://tempuri.org/IUser/GetAllUserResponse")]
        BanHang.ServiceUser.user[] GetAllUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetAllUser", ReplyAction="http://tempuri.org/IUser/GetAllUserResponse")]
        System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> GetAllUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserById", ReplyAction="http://tempuri.org/IUser/GetUserByIdResponse")]
        BanHang.ServiceUser.user GetUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserById", ReplyAction="http://tempuri.org/IUser/GetUserByIdResponse")]
        System.Threading.Tasks.Task<BanHang.ServiceUser.user> GetUserByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserByEmail", ReplyAction="http://tempuri.org/IUser/GetUserByEmailResponse")]
        BanHang.ServiceUser.user GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserByEmail", ReplyAction="http://tempuri.org/IUser/GetUserByEmailResponse")]
        System.Threading.Tasks.Task<BanHang.ServiceUser.user> GetUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/FindUserByEmail", ReplyAction="http://tempuri.org/IUser/FindUserByEmailResponse")]
        BanHang.ServiceUser.user[] FindUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/FindUserByEmail", ReplyAction="http://tempuri.org/IUser/FindUserByEmailResponse")]
        System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> FindUserByEmailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserByName", ReplyAction="http://tempuri.org/IUser/GetUserByNameResponse")]
        BanHang.ServiceUser.user[] GetUserByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUserByName", ReplyAction="http://tempuri.org/IUser/GetUserByNameResponse")]
        System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> GetUserByNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AddUser", ReplyAction="http://tempuri.org/IUser/AddUserResponse")]
        bool AddUser(BanHang.ServiceUser.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/AddUser", ReplyAction="http://tempuri.org/IUser/AddUserResponse")]
        System.Threading.Tasks.Task<bool> AddUserAsync(BanHang.ServiceUser.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUser", ReplyAction="http://tempuri.org/IUser/UpdateUserResponse")]
        bool UpdateUser(BanHang.ServiceUser.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/UpdateUser", ReplyAction="http://tempuri.org/IUser/UpdateUserResponse")]
        System.Threading.Tasks.Task<bool> UpdateUserAsync(BanHang.ServiceUser.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/DeleteUser", ReplyAction="http://tempuri.org/IUser/DeleteUserResponse")]
        bool DeleteUser(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/DeleteUser", ReplyAction="http://tempuri.org/IUser/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : BanHang.ServiceUser.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<BanHang.ServiceUser.IUser>, BanHang.ServiceUser.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckUser(string email, string pass) {
            return base.Channel.CheckUser(email, pass);
        }
        
        public System.Threading.Tasks.Task<bool> CheckUserAsync(string email, string pass) {
            return base.Channel.CheckUserAsync(email, pass);
        }
        
        public bool CheckEmailExisted(string email) {
            return base.Channel.CheckEmailExisted(email);
        }
        
        public System.Threading.Tasks.Task<bool> CheckEmailExistedAsync(string email) {
            return base.Channel.CheckEmailExistedAsync(email);
        }
        
        public BanHang.ServiceUser.user[] GetAllUser() {
            return base.Channel.GetAllUser();
        }
        
        public System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> GetAllUserAsync() {
            return base.Channel.GetAllUserAsync();
        }
        
        public BanHang.ServiceUser.user GetUserById(int id) {
            return base.Channel.GetUserById(id);
        }
        
        public System.Threading.Tasks.Task<BanHang.ServiceUser.user> GetUserByIdAsync(int id) {
            return base.Channel.GetUserByIdAsync(id);
        }
        
        public BanHang.ServiceUser.user GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<BanHang.ServiceUser.user> GetUserByEmailAsync(string email) {
            return base.Channel.GetUserByEmailAsync(email);
        }
        
        public BanHang.ServiceUser.user[] FindUserByEmail(string email) {
            return base.Channel.FindUserByEmail(email);
        }
        
        public System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> FindUserByEmailAsync(string email) {
            return base.Channel.FindUserByEmailAsync(email);
        }
        
        public BanHang.ServiceUser.user[] GetUserByName(string name) {
            return base.Channel.GetUserByName(name);
        }
        
        public System.Threading.Tasks.Task<BanHang.ServiceUser.user[]> GetUserByNameAsync(string name) {
            return base.Channel.GetUserByNameAsync(name);
        }
        
        public bool AddUser(BanHang.ServiceUser.user user) {
            return base.Channel.AddUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> AddUserAsync(BanHang.ServiceUser.user user) {
            return base.Channel.AddUserAsync(user);
        }
        
        public bool UpdateUser(BanHang.ServiceUser.user user) {
            return base.Channel.UpdateUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateUserAsync(BanHang.ServiceUser.user user) {
            return base.Channel.UpdateUserAsync(user);
        }
        
        public bool DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(int id) {
            return base.Channel.DeleteUserAsync(id);
        }
    }
}
