//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBH_PHONE_SERVICE.Models
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(save))]
    
    public partial class save_date
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int id_save { get; set; }
    	[DataMember]
        public System.DateTime date_start { get; set; }
    	[DataMember]
        public System.DateTime date_end { get; set; }
    	[DataMember]
        public string content { get; set; }
    
    	[DataMember]
        public virtual save save { get; set; }
    }
}
